-- Migration 001: retired.
--
-- Originally updated organizations.subdomain and backfilled @bsc.demo ->
-- @bsc.rw user emails. subdomain was removed from the schema entirely
-- (backend/models/organization.py) - it was never used for tenant
-- detection (email_domain handles that) and this migration had assumed
-- the column already existed, so it never actually ran successfully
-- against Postgres (UndefinedColumn on every attempt, silently retried
-- and failing on every single startup since it was added). Left as a
-- no-op rather than deleted so migration numbering/history stays intact.
