-- Migration 002: retired.
--
-- Originally added organizations.email_domain, split demo/BSC orgs, and
-- created admin@demo.com. Written in MySQL syntax (ON DUPLICATE KEY
-- UPDATE, INSERT IGNORE, UUID(), COMMENT on ALTER COLUMN) against a
-- Postgres database, so it never once executed successfully - every
-- attempt failed at the very first statement's syntax error, meaning
-- none of its effects (including the subdomain backfill, since removed
-- from the schema - see migration 001) ever applied. Superseded by
-- database/seeds/001_organizations.sql and the seed_*.py scripts, which
-- already create both organizations correctly. Left as a no-op rather
-- than deleted so migration numbering/history stays intact.
